## Numpy 알아보기
##### Numpy 는 n 차원으로 이루어진 배열(array)를 연산할 수 있는 모듈이며, Cpp로 이루어져 있어 연산 속도가 빠름. 흔히 행렬 계산하는데 쓰인다.

In [2]:
import numpy as np
import pandas as pd

In [3]:
array1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [4]:
print(array1)
type(array1) 
# 주피터 노트북에서는 마지막 줄을 프린트로 내보낼 수 있는 경우 output 으로 내보낸다.
# 개행을 하고 마지막 줄 아닌 값도 출력하고 싶으면 프린트로 해주셈. 
# 또한 out  put 이 거슬리면 둘다 프린트로 묶어줘도 됨.

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [5]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[12,13,14,15]])
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [12 13 14 15]]


In [6]:
array2.shape # (행, 열) 갯수 이렇게 나오는 듯? 

(4, 4)

##### np.zeros() , np.ones(), np.arange() 함수들

In [8]:
np.zeros((3,3)) # parameter 에 (행,열) 을 넣어줘야함. 괄호로 묶어

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.arange(0,31,2) # start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

###### 비슷한 함수로는 python 기본 함수인 range 가 있음

In [12]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


##### array 연산

In [14]:
test_list1 = [1,2,3,4,5]
test_list2 = [6,7,8,9,10]

In [15]:
test_list1 + test_list2 
# list 연산의 경우 그냥 나열만 됨으로 같은 차원의 원소끼리 덧셈이 안됨.
# 따라서 이러한 경우에는 np.array 연산을 해주는 것!
# 다만 배열의 연산은 행렬의 연산처럼 되는 것은 아니다.

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
array3 = np.array([[1,2,3],[4,5,6]])

In [17]:
print(array3 * array3)

[[ 1  4  9]
 [16 25 36]]


In [18]:
print(array3+array3)

[[ 2  4  6]
 [ 8 10 12]]


In [19]:
print(1/array3)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [20]:
array4 = np.array([[4,4,1],[7,2,12]])

In [21]:
print(array3*array4,"\n", 
      array3/array4,"\n",
      array4+array3)

[[ 4  8  3]
 [28 10 72]] 
 [[0.25       0.5        3.        ]
 [0.57142857 2.5        0.5       ]] 
 [[ 5  6  4]
 [11  7 18]]


##### indexing slicing

In [23]:
array5 = np.arange(10)
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
array5[5]

5

In [25]:
array5[1:4]

array([1, 2, 3])

In [26]:
array6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array6[0]

array([1, 2, 3])

In [28]:
array6[0][1]

2

In [29]:
array6[-1][-1] # [-1][-1] # 배열의 원소에 마지막 원소가 뽑힘

9

### 넘파이 통계 함수

In [31]:
array8 = np.random.randn(7,4)
print(array8)

[[-0.78421533  1.35297947 -1.06134029 -0.33461257]
 [ 0.78010578 -0.55417135  0.06382516  0.83639699]
 [-0.99408747 -0.5437     -0.37193676  0.19437301]
 [ 0.9539991  -2.01692179  1.34502569 -1.46872656]
 [-0.59551598  1.56276592  0.47867224  0.11211346]
 [-0.25264389 -1.24107111 -0.31026605 -0.54292564]
 [ 1.48323931 -1.12590163 -1.4936075   1.20237891]]


In [32]:
print(np.sum(array8)) # np.sum() 는 행렬 계산이 아닌 원소 계산을 하기 때문에 
# 행렬, 배열, 리스트 전부 다 가능 하다.
print(np.sum([10,20,30]))

-3.3257688781853667
60


In [33]:
print("Rows sum:\n",np.sum(array8, axis = 1)) # row 을 기준으로 합해서 row 갯수만큼 나옴
print("Columns sum:\n",np.sum(array8, axis = 0)) # column 을 기준으로 합해서 column 갯수만큼 나옴

Rows sum:
 [-0.82718872  1.12615658 -1.71535122 -1.18662356  1.55803564 -2.34690668
  0.06610909]
Columns sum:
 [ 5.90881512e-01 -2.56602050e+00 -1.34962751e+00 -1.00238032e-03]


In [34]:
print(np.mean(array8))
print(np.mean(array8, axis = 1))
print(np.mean(array8, axis =0))

-0.11877745993519166
[-0.20679718  0.28153915 -0.42883781 -0.29665589  0.38950891 -0.58672667
  0.01652727]
[ 8.44116446e-02 -3.66574358e-01 -1.92803929e-01 -1.43197188e-04]


In [35]:
print("totla std:", np.std(array8))
print("rows std:", np.std(array8, axis = 1))
print("columns std:",np.std(array8, axis =0))

totla std: 0.9908588552764234
rows std: [0.93713601 0.57058026 0.42553788 1.46563303 0.77969615 0.39310525
 1.33633259]
columns std: [0.90162335 1.2427363  0.87619224 0.82457925]


In [36]:
print("totla median:", np.median(array8))
print("rows median:", np.median(array8, axis = 1))
print("columns median:",np.median(array8, axis =0))

totla median: -0.3224393068276147
rows median: [-0.55941395  0.42196547 -0.45781838 -0.25736373  0.29539285 -0.42659584
  0.03823864]
columns median: [-0.25264389 -0.55417135 -0.31026605  0.11211346]


In [72]:
test_array = array8[0]
print(test_array)
print(np.argmin(test_array)) # 배열의 가장 작은 원소의 인덱스를 반환
print(np.argmax(test_array)) # 배열의 가장 큰 원소의 인덱스를 반환

[-0.78421533  1.35297947 -1.06134029 -0.33461257]
2
1


In [38]:
print(np.cumsum(test_array)) # cumulate sum 0번째 인덱스부터 계속해서 더 해준 값을 반환
print(np.cumprod(test_array)) # cumulate product 0번째 인덱스부터 계속해서 곱해준 값을 반환

[-0.78421533  0.56876414 -0.49257616 -0.82718872]
[-0.78421533 -1.06102724  1.12611096 -0.37681088]


In [78]:
array9 = np.random.randn(5,3)
print(array9)

[[-0.28539026  0.40580327  0.23948845]
 [-0.06414439  0.83080648  1.83960278]
 [-0.06164704  0.18822261 -0.29747243]
 [ 0.80547344 -0.68763167  0.01212938]
 [-0.978994    0.57729452  0.95389834]]


In [84]:
print(np.sqrt(array9))
print(np.square(array9))
print(np.abs(array9))
print(np.log(array9))
print(np.exp(array9))
print(np.sign(array9))
print(np.cell(array9))

[[       nan 0.6370269  0.48937557]
 [       nan 0.91148587 1.35631957]
 [       nan 0.4338463         nan]
 [0.89748172        nan 0.11013346]
 [       nan 0.759799   0.9766772 ]]
[[8.14475983e-02 1.64676295e-01 5.73547172e-02]
 [4.11450309e-03 6.90239414e-01 3.38413840e+00]
 [3.80035788e-03 3.54277509e-02 8.84898477e-02]
 [6.48787459e-01 4.72837318e-01 1.47121853e-04]
 [9.58429260e-01 3.33268959e-01 9.09922050e-01]]
[[0.28539026 0.40580327 0.23948845]
 [0.06414439 0.83080648 1.83960278]
 [0.06164704 0.18822261 0.29747243]
 [0.80547344 0.68763167 0.01212938]
 [0.978994   0.57729452 0.95389834]]
[[        nan -0.90188679 -1.42925009]
 [        nan -0.18535838  0.60954967]
 [        nan -1.67012992         nan]
 [-0.21632505         nan -4.41212469]
 [        nan -0.54940271 -0.04719817]]
[[0.75172083 1.50050733 1.27059901]
 [0.93786957 2.29516901 6.29403766]
 [0.94021468 1.2071022  0.74269306]
 [2.23775569 0.50276537 1.01220324]
 [0.37568885 1.78121286 2.59580932]]
[[-1.  1.  1.]
 [-1.

C:\Users\agy91\AppData\Local\Temp\ipykernel_1572\2109119308.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(array9))
C:\Users\agy91\AppData\Local\Temp\ipykernel_1572\2109119308.py:4: RuntimeWarning: invalid value encountered in log
  print(np.log(array9))


AttributeError: module 'numpy' has no attribute 'cell'